version: "3.9"

services:

  web:
    container_name: nginx
    image: nginx:stable
    depends_on:
      - php
    working_dir: /var/www/symfony/
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/symfony
      - ./config/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php-fpm81
    hostname: php-docker-service
    build:
      context: config/docker
      dockerfile: Dockerfile
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/symfony
      - ./config/docker/docker-xdebug-php.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    environment:
      PHP_IDE_CONFIG: "serverName=php-fpm8_Docker"
      XDEBUG_SESSION: 1
      XDEBUG_CONFIG: "remote_enable=1 remote_autostart=1 remote_host=192.168.0.101"

  db:
      container_name: postgres
      depends_on:
          - php
      image: postgres:14
      restart: always
      environment:
          DB_CONNECTION: pgsql
          POSTGRES_DB: newsdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: qwer1
          PGDATA: "/var/lib/postgresql/data/pgdata"
      volumes:
          - /home/amicofideli/PhpstormProjects/symfony-news-feed/database:/var/lib/postgresql/data
      ports:
          - 5432:5432

  adminer:
      container_name: adminer
      depends_on:
          - db
      image: adminer
      restart: always
      ports:
          - 8081:8080
